<?php

namespace app\en_us\controller;

use app\common\helper\Category as CategoryHelp;
use app\common\model\Category as CategoryModel;
use app\common\model\Language as LanguageModel;

class  Category extends Base
{

    protected $navbar;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $data = collection((new CategoryModel())->getDataByCode($this->code))->toArray();
        $tree = CategoryHelp::toLayer($data, $name = 'title', $parent_id = 0);
        $this->assign('tree', $tree);
    }

    /***
     * winstars 产品列表封面页
     * @return mixed
     */
    public function index()
    {
        return $this->fetch(
            $this->template . '/category/index.html');
    }

    /***
     * 根据分类来获取产品数据
     * 20190403
     * 邱锦
     * @param string $category
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function category($category = "")
    {
        if (empty($category)) {
            abort(404);
        }
        $categoryModel = new CategoryModel();
        $cate = $categoryModel->getAllCategory($this->code);
        $language_id = LanguageModel::getLanguageCodeOrID($this->code);
        $category_data = (new CategoryModel())->getCategoryByName($category, $language_id);
        //产品详情页路径导航
        $path = collection(CategoryHelp::getParents($cate, $category_data['id']))->toArray();
        $data = CategoryModel::getCategoryWithProduct($category_data['id']);
        $page = $data->render();
        return $this->fetch($this->template . '/category/list.html', ["cate" => $category, "category" => $category_data, "result" => $data, "page" => $page, "path" => $path, "count" => count($data)]);
    }

}