<?php

namespace app\en_us\controller;

use app\common\helper\Category as CategoryHelp;
use app\common\model\Category as CategoryModel;
use app\common\model\Product as ProductModel;
use app\common\model\Language as LanguageModel;

class Product extends Base
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $best = (new ProductModel())->getBestSales($this->code)->toArray();
        $albums = explode(',', $best['album']);
        $best['album'] = $albums[0];
        $this->assign('bestSales', $best);
    }

    public function index()
    {
        abort(404);
    }

    public function details($product = '')
    {
        if (!isset($product) || empty($product)) {
            abort(404);
        }
        $result = (new ProductModel())->getDetailByUrlTitle($product, $this->code);
        if (!empty($result['data'])) {
            if (!empty($result['data']['album'])) {
                //产品详情页放大镜的图
                $result['data']['albums'] = explode(',', $result['data']['album']);
                $albums = explode(',', $result['data']['album']);
                $this->assign('albums', $albums);
                $this->assign('album', $albums[0]);
            }
            $language_id = LanguageModel::getLanguageCodeOrID($this->code);
            $category_id = (new ProductModel())->getCategoryById($result['data']->id);
            $category_data = (new CategoryModel())->getCategoryById($this->code, $category_id);
            $this->assign("category", $category_data);
            $result = $result['data']->toArray();
            return $this->fetch($this->template . '/product/details.html', [
                'result' => $result,
            ]);
        } else {
            abort(404);
        }
    }
}